AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Resources:
  ApiTierAlb:
    Properties:
      Subnets:
        - Fn::ImportValue: !Sub "${NetworksStackNameParm}-PublicGeneralPurposeSubnetAOutput"
        - Fn::ImportValue: !Sub "${NetworksStackNameParm}-PublicGeneralPurposeSubnetBOutput"
        - Fn::ImportValue: !Sub "${NetworksStackNameParm}-PublicGeneralPurposeSubnetCOutput"
      SecurityGroups:
        - Fn::ImportValue: !Sub "${NetworksStackNameParm}-AppTierAlbSecurityGroupIdOutput"
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
  ApiTierAlbSslListener:
    Properties:
      LoadBalancerArn: !Ref ApiTierAlb
      DefaultActions:
        - TargetGroupArn: !Ref ApiTierAlbTargetGroup
          Type: forward
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref AcmCertArnParm
    Type: AWS::ElasticLoadBalancingV2::Listener
  ApiTierAlbCname:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: A
      HostedZoneName:
        "Fn::Join":
          - ""
          - - !Ref DomainNameParm
            - "."
      Name:
        "Fn::Join":
          - ""
          - - !Ref HostNameParm
            - "."
            - !Ref DomainNameParm
      AliasTarget:
        HostedZoneId: !GetAtt ApiTierAlb.CanonicalHostedZoneID
        DNSName: !GetAtt ApiTierAlb.DNSName

  ApiTierAlbTargetGroup:
    Properties:
      HealthCheckPath:
        "Fn::Join":
          - ""
          - - "/"
            - !Ref ContextRootParm
            - "/"
            - !Ref HealthCheckPathParm
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      HealthCheckPort: !Ref HealthCheckPortParm
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 3
      VpcId:
        Fn::ImportValue: !Sub "${NetworksStackNameParm}-VpcIdOutput"
      Port: 8080
      Protocol: HTTP
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
  ApiTierAlbListenerRule:
    Properties:
      Actions:
        - TargetGroupArn: !Ref ApiTierAlbTargetGroup
          Type: forward
      Conditions:
        - Field: path-pattern
          Values:
            - !Ref EnvironmentParm
      ListenerArn: !Ref ApiTierAlbSslListener
      Priority: 100
    Type: AWS::ElasticLoadBalancingV2::ListenerRule

  ApiTierAutoscalingGroup:
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MaxBatchSize: 1
        MinInstancesInService: !Ref ApiTierAsgDesiredCapacityParm
        SuspendProcesses:
          - HealthCheck
          - ReplaceUnhealthy
          - AZRebalance
          - AlarmNotification
          - ScheduledActions
    Properties:
      MaxSize: !Ref ApiTierAsgMaxSizeParm
      HealthCheckType: ELB
      TargetGroupARNs:
        - !Ref ApiTierAlbTargetGroup
      MinSize: !Ref ApiTierAsgMinSizeParm
      AvailabilityZones: !Ref ApiTierAsgAzsParm
      DesiredCapacity: !Ref ApiTierAsgDesiredCapacityParm
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub "${NetworksStackNameParm}-PrivateGeneralPurposeSubnetAOutput"
        - Fn::ImportValue: !Sub "${NetworksStackNameParm}-PrivateGeneralPurposeSubnetBOutput"
        - Fn::ImportValue: !Sub "${NetworksStackNameParm}-PrivateGeneralPurposeSubnetCOutput"
      HealthCheckGracePeriod: !Ref HealthCheckGracePeriodParm
      LaunchConfigurationName:
        Fn::ImportValue:
          !Sub "${LaunchConfigurationStackNameParm}-ApiTierLaunchConfigurationOutput"
      Tags:
        - Key: Name
          Value: !Ref NameTagParm
          PropagateAtLaunch: True
        - Key: Environment
          Value: !Ref EnvironmentParm
          PropagateAtLaunch: True
    Type: AWS::AutoScaling::AutoScalingGroup
  ApiTierScaleOutPolicy:
    Properties:
      AutoScalingGroupName: !Ref ApiTierAutoscalingGroup
      AdjustmentType: ChangeInCapacity
      PolicyType: SimpleScaling
      ScalingAdjustment: 1
    Type: AWS::AutoScaling::ScalingPolicy
  ApiTierCpuCreditsUsageHighAlarm:
    Properties:
      ComparisonOperator: GreaterThanThreshold
      Threshold: !Ref ApiTierCpuCreditsUsageHighThresholdParm
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref ApiTierAutoscalingGroup
      EvaluationPeriods: 1
      MetricName: CPUCreditUsage
      Namespace: AWS/EC2
      Period: 300
      Statistic: Average
      AlarmActions:
        - !Ref ApiTierScaleOutPolicy
    Type: AWS::CloudWatch::Alarm
  ApiTierScaleInPolicy:
    Properties:
      AutoScalingGroupName: !Ref ApiTierAutoscalingGroup
      AdjustmentType: ChangeInCapacity
      PolicyType: SimpleScaling
      ScalingAdjustment: -1
    Type: AWS::AutoScaling::ScalingPolicy
  ApiTierCpuCreditsUsageLowAlarm:
    Properties:
      ComparisonOperator: LessThanThreshold
      Threshold: !Ref ApiTierCpuCreditsUsageLowThresholdParm
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref ApiTierAutoscalingGroup
      EvaluationPeriods: 36
      MetricName: CPUCreditUsage
      Namespace: AWS/EC2
      Period: 300
      Statistic: Average
      AlarmActions:
        - !Ref ApiTierScaleInPolicy
    Type: AWS::CloudWatch::Alarm
Parameters:
  EnvironmentParm:
    Type: String
  ApiTierAsgMinSizeParm:
    Type: String
  ApiTierAsgMaxSizeParm:
    Type: String
  ApiTierAsgDesiredCapacityParm:
    Type: String
  ApiTierAsgAzsParm:
    Type: List<AWS::EC2::AvailabilityZone::Name>




  LaunchConfigurationStackNameParm:
    Type: String
  NetworksStackNameParm:
    Type: String

  ApiTierCpuCreditsUsageHighThresholdParm:
    Type: Number
  ApiTierCpuCreditsUsageLowThresholdParm:
    Type: Number
  HealthCheckPathParm:
    Type: String
  DomainNameParm:
    Type: String
  HostNameParm:
    Type: String
  HealthCheckGracePeriodParm:
    Type: Number
  HealthCheckPortParm:
    Type: Number
  ContextRootParm:
    Type: String
  AcmCertArnParm:
    Type: String
  NameTagParm:
    Type: String
